INSERT INTO file
    (file_id, original_name, stored_name, file_path, content_type, file_size, created_at, updated_at)
VALUES
      (UUID_TO_BIN(UUID()), 'busan.jpg', '동백전.jpg', '/static/images/localCurrency/busan.jpg', 'jpg', 18007, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daegu.jpg', '대구로페이.jpg', '/static/images/localCurrency/daegu.jpg', 'jpg', 25875, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gunsan.jpg', '군산사랑상품권.jpg', '/static/images/localCurrency/gunsan.jpg', 'jpg', 65580, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gwangju.jpg', '광주상생카드.jpg', '/static/images/localCurrency/gwangju.jpg', 'jpg', 19205, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'iksan.jpg', '익산다이로움카드.jpg', '/static/images/localCurrency/iksan.jpg', 'jpg', 39744, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeju.jpg', '탐나는전.jpg', '/static/images/localCurrency/jeju.jpg', 'jpg', 19673, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'ulsan.jpg', '울산페이.jpg', '/static/images/localCurrency/ulsan.jpg', 'jpg', 18398, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'seoul1.webp', '서울금뱃지.webp', '/static/images/badge/seoul1.webp', 'webp', 934946, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'seoul2.webp', '서울은뱃지.webp', '/static/images/badge/seoul2.webp', 'webp', 1008482, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'seoul3.webp', '서울동뱃지.webp', '/static/images/badge/seoul3.webp', 'webp', 1212984, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'busan1.webp', '부산금뱃지.webp', '/static/images/badge/busan1.webp', 'webp', 1138040, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'busan2.webp', '부산은뱃지.webp', '/static/images/badge/busan2.webp', 'webp', 1003932, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'busan3.webp', '부산동뱃지.webp', '/static/images/badge/busan3.webp', 'webp', 1154512, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daegu1.webp', '대구금뱃지.webp', '/static/images/badge/daegu1.webp', 'webp', 1110660, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daegu2.webp', '대구은뱃지.webp', '/static/images/badge/daegu2.webp', 'webp', 1058746, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daegu3.webp', '대구동뱃지.webp', '/static/images/badge/daegu3.webp', 'webp', 969080, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'incheon1.webp', '인천금뱃지.webp', '/static/images/badge/incheon1.webp', 'webp', 1188148, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'incheon2.webp', '인천은뱃지.webp', '/static/images/badge/incheon2.webp', 'webp', 194298, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'incheon3.webp', '인천동뱃지.webp', '/static/images/badge/incheon3.webp', 'webp', 276214, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gwangju1.webp', '광주금뱃지.webp', '/static/images/badge/gwangju1.webp', 'webp', 249682, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gwangju2.webp', '광주은뱃지.webp', '/static/images/badge/gwangju2.webp', 'webp', 262814, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gwangju3.webp', '광주동뱃지.webp', '/static/images/badge/gwangju3.webp', 'webp', 257150, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daejeon1.webp', '대전금뱃지.webp', '/static/images/badge/daejeon1.webp', 'webp', 167440, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daejeon2.webp', '대전은뱃지.webp', '/static/images/badge/daejeon2.webp', 'webp', 231392, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daejeon3.webp', '대전동뱃지.webp', '/static/images/badge/daejeon3.webp', 'webp', 228620, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'ulsan1.webp', '울산금뱃지.webp', '/static/images/badge/ulsan1.webp', 'webp', 251286, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'ulsan2.webp', '울산은뱃지.webp', '/static/images/badge/ulsan2.webp', 'webp', 166956, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'ulsan3.webp', '울산동뱃지.webp', '/static/images/badge/ulsan3.webp', 'webp', 245764, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'sejong1.webp', '세종금뱃지.webp', '/static/images/badge/sejong1.webp', 'webp', 191322, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'sejong2.webp', '세종은뱃지.webp', '/static/images/badge/sejong2.webp', 'webp', 276086, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'sejong3.webp', '세종동뱃지.webp', '/static/images/badge/sejong3.webp', 'webp', 207888, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeonggi1.webp', '경기금뱃지.webp', '/static/images/badge/gyeonggi1.webp', 'webp', 186482, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeonggi2.webp', '경기은뱃지.webp', '/static/images/badge/gyeonggi2.webp', 'webp', 192862, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeonggi3.webp', '경기동뱃지.webp', '/static/images/badge/gyeonggi3.webp', 'webp', 350174, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gangwon1.webp', '강원금뱃지.webp', '/static/images/badge/gangwon1.webp', 'webp', 36014, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gangwon2.webp', '강원은뱃지.webp', '/static/images/badge/gangwon2.webp', 'webp', 27880, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gangwon3.webp', '강원동뱃지.webp', '/static/images/badge/gangwon3.webp', 'webp', 34042, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungbuk1.webp', '충북금뱃지.webp', '/static/images/badge/chungbuk1.webp', 'webp', 146760, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungbuk2.webp', '충북은뱃지.webp', '/static/images/badge/chungbuk2.webp', 'webp', 134100, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungbuk3.webp', '충북동뱃지.webp', '/static/images/badge/chungbuk3.webp', 'webp', 115060, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungnam1.webp', '충남금뱃지.webp', '/static/images/badge/chungnam1.webp', 'webp', 77506, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungnam2.webp', '충남은뱃지.webp', '/static/images/badge/chungnam2.webp', 'webp', 89822, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungnam3.webp', '충남동뱃지.webp', '/static/images/badge/chungnam3.webp', 'webp', 103042, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonbuk1.webp', '전북금뱃지.webp', '/static/images/badge/jeonbuk1.webp', 'webp', 157872, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonbuk2.webp', '전북은뱃지.webp', '/static/images/badge/jeonbuk2.webp', 'webp', 100412, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonbuk3.webp', '전북동뱃지.webp', '/static/images/badge/jeonbuk3.webp', 'webp', 123282, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonnam1.webp', '전남금뱃지.webp', '/static/images/badge/jeonnam1.webp', 'webp', 154406, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonnam2.webp', '전남은뱃지.webp', '/static/images/badge/jeonnam2.webp', 'webp', 188332, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonnam3.webp', '전남동뱃지.webp', '/static/images/badge/jeonnam3.webp', 'webp', 168140, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongbuk1.webp', '경북금뱃지.webp', '/static/images/badge/gyeongbuk1.webp', 'webp', 117848, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongbuk2.webp', '경북은뱃지.webp', '/static/images/badge/gyeongbuk2.webp', 'webp', 93218, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongbuk3.webp', '경북동뱃지.webp', '/static/images/badge/gyeongbuk3.webp', 'webp', 156960, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongnam1.webp', '경남금뱃지.webp', '/static/images/badge/gyeongnam1.webp', 'webp', 74040, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongnam2.webp', '경남은뱃지.webp', '/static/images/badge/gyeongnam2.webp', 'webp', 93828, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongnam3.webp', '경남동뱃지.webp', '/static/images/badge/gyeongnam3.webp', 'webp', 67688, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeju1.webp', '제주금뱃지.webp', '/static/images/badge/jeju1.webp', 'webp', 24926, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeju2.webp', '제주은뱃지.webp', '/static/images/badge/jeju2.webp', 'webp', 135852, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeju3.webp', '제주동뱃지.webp', '/static/images/badge/jeju3.webp', 'webp', 135790, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'seoulspecial.webp', '서울특별뱃지.webp', '/static/images/badge/seoulspecial.webp', 'webp', 56992, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'busanspecial.webp', '부산특별뱃지.webp', '/static/images/badge/busanspecial.webp', 'webp', 25816, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daeguspecial.webp', '대구특별뱃지.webp', '/static/images/badge/daeguspecial.webp', 'webp', 46554, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'incheonspecial.webp', '인천특별뱃지.webp', '/static/images/badge/incheonspecial.webp', 'webp', 47834, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gwangjuspecial.webp', '광주특별뱃지.webp', '/static/images/badge/gwangjuspecial.webp', 'webp', 45266, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'daejeonspecial.webp', '대전특별뱃지.webp', '/static/images/badge/daejeonspecial.webp', 'webp', 52682, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'ulsanspecial.webp', '울산특별뱃지.webp', '/static/images/badge/ulsanspecial.webp', 'webp', 49132, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'sejongspecial.webp', '세종특별뱃지.webp', '/static/images/badge/sejongspecial.webp', 'webp', 37362, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeonggispecial.webp', '경기특별뱃지.webp', '/static/images/badge/gyeonggispecial.webp', 'webp', 51742, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gangwonspecial.webp', '강원특별뱃지.webp', '/static/images/badge/gangwonspecial.webp', 'webp', 76006, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungbukspecial.webp', '충북특별뱃지.webp', '/static/images/badge/chungbukspecial.webp', 'webp', 52360, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'chungnamspecial.webp', '충남특별뱃지.webp', '/static/images/badge/chungnamspecial.webp', 'webp', 53600, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonbukspecial.webp', '전북특별뱃지.webp', '/static/images/badge/jeonbukspecial.webp', 'webp', 57620, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jeonnamspecial.webp', '전남특별뱃지.webp', '/static/images/badge/jeonnamspecial.webp', 'webp', 46980, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongbukspecial.webp', '경북특별뱃지.webp', '/static/images/badge/gyeongbukspecial.webp', 'webp', 51816, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'gyeongnamspecial.webp', '경남특별뱃지.webp', '/static/images/badge/gyeongnamspecial.webp', 'webp', 45546, NOW(), NOW()),
      (UUID_TO_BIN(UUID()), 'jejuspecial.webp', '제주특별뱃지.webp', '/static/images/badge/jejuspecial.webp', 'webp', 44968, NOW(), NOW());


INSERT INTO file_reference
(file_reference_id, file_id, reference_type, reference_id, usage_type, created_at, updated_at)
VALUES
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'busan.jpg'), 'local_currency', (SELECT local_currency_id FROM local_currency WHERE name = '동백전'), 'card_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daegu.jpg'), 'local_currency', (SELECT local_currency_id FROM local_currency WHERE name = '대구로페이'), 'card_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gunsan.jpg'), 'local_currency', (SELECT local_currency_id FROM local_currency WHERE name = '군산사랑상품권'), 'card_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gwangju.jpg'), 'local_currency', (SELECT local_currency_id FROM local_currency WHERE name = '광주상생카드'), 'card_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'iksan.jpg'), 'local_currency', (SELECT local_currency_id FROM local_currency WHERE name = '익산다이로움카드'), 'card_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeju.jpg'), 'local_currency', (SELECT local_currency_id FROM local_currency WHERE name = '탐나는전'), 'card_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'ulsan.jpg'), 'local_currency', (SELECT local_currency_id FROM local_currency WHERE name = '울산페이'), 'card_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'seoul1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '서울특별시'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'seoul2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '서울특별시'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'seoul3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '서울특별시'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'busan1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '반짝반짝 광안대교'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'busan2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '반짝반짝 광안대교'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'busan3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '반짝반짝 광안대교'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daegu1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '수줍은 사과'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daegu2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '수줍은 사과'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daegu3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '수줍은 사과'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daegu3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '수줍은 사과'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'incheon1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '떴다떴다 비행기'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'incheon2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '떴다떴다 비행기'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'incheon3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '떴다떴다 비행기'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gwangju1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '빛고을 반짝이'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gwangju2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '빛고을 반짝이'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gwangju3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '빛고을 반짝이'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daejeon1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '공공칠빵'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daejeon2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '공공칠빵'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daejeon3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '공공칠빵'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'ulsan1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '고래의 콧바람'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'ulsan2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '고래의 콧바람'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'ulsan3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '고래의 콧바람'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'sejong1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '세종대왕의 붓끝'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'sejong2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '세종대왕의 붓끝'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'sejong3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '세종대왕의 붓끝'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeonggi1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '별빛 수원화성'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeonggi2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '별빛 수원화성'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeonggi3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '별빛 수원화성'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gangwon1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '행운의 감자'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gangwon2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '행운의 감자'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gangwon3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '행운의 감자'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungbuk1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '퐁퐁 포도알'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungbuk2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '퐁퐁 포도알'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungbuk3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '퐁퐁 포도알'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungnam1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '행복한 딸기요정'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungnam2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '행복한 딸기요정'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungnam3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '행복한 딸기요정'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonbuk1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '비벼비벼 행운밥'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonbuk2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '비벼비벼 행운밥'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonbuk3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '비벼비벼 행운밥'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonnam1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '영광스런 굴비'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonnam2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '영광스런 굴비'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonnam3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '영광스런 굴비'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongbuk1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '되게 행복한 대게'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongbuk2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '되게 행복한 대게'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongbuk3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '되게 행복한 대게'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongnam1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '반짝반짝 행운밤'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongnam2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '반짝반짝 행운밤'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongnam3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '반짝반짝 행운밤'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeju1.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '돌하르방의 청혼'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeju2.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '돌하르방의 청혼'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeju3.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '돌하르방의 청혼'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'seoulspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '불꽃축제의 밤'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'busanspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '부산 불꽃축제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daeguspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '치맥페스티벌'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'incheonspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '인천 펜타포트'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gwangjuspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '광주 비엔날레'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'daejeonspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '대전 사이언스 페스타'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'ulsanspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '울산 고래축제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'sejongspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '세종 문화축제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeonggispecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '수원화성문화제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gangwonspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '강릉 단오제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungbukspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '청원 생명축제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'chungnamspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '논산 딸기축제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonbukspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '전주 한지문화제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jeonnamspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '보성 녹차대축제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongbukspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '안동 탈춤페스티벌'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'gyeongnamspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '진주 남강유등축제'), 'badge_image', NOW(), NOW()),
    (UUID_TO_BIN(UUID()), (SELECT file_id FROM file WHERE original_name = 'jejuspecial.webp'), 'badge', (SELECT badge_id FROM badge WHERE name = '제주 들불축제'), 'badge_image', NOW(), NOW());








