
SET FOREIGN_KEY_CHECKS = 0;

-- 불필요한 시퀀스 테이블 삭제
DROP TABLE IF EXISTS BATCH_JOB_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;


SET FOREIGN_KEY_CHECKS = 1;